---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-green
  namespace: bluegreentest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
      color: green
  template:
    metadata:
      labels:
        app: testapp
        color: green
    spec:
      containers:
      - name: testapp-green
        image: fblzs/bluegreenapp:greenv2
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        - name: ASPNETCORE_URLS
          value: "http://+;"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 1
