---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-{{{DEPLOYMENT}}}
  namespace: bluegreentest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
      color: {{{DEPLOYMENT}}}
  template:
    metadata:
      labels:
        app: testapp
        color: {{{DEPLOYMENT}}}
    spec:
      containers:
      - name: testapp-{{{DEPLOYMENT}}}
        image: fblzs/bluegreenapp:{{{DEPLOYMENT}}}v3
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        - name: ASPNETCORE_URLS
          value: "http://+;"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1