---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-blue
  namespace: bluegreentest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
      color: blue
  template:
    metadata:
      labels:
        app: testapp
        color: blue
    spec:
      containers:
      - name: testapp-blue
        image: fblzs/bluegreenapp:bluev4
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        - name: ASPNETCORE_URLS
          value: "http://+;"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
          - name: secrets
            mountPath: "/app/secrets"
            readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: testapp-secrets